name = "nextjs-vendure"
pages_build_output_dir = ".open-next/assets"
compatibility_date = "2026-04-23"
compatibility_flags = ["nodejs_compat"]

[vars]
VENDURE_SHOP_API_URL = "https://my-vendure-shop-production-492b.up.railway.app/shop-api"
NEXT_PUBLIC_VENDURE_SHOP_API_URL = "https://my-vendure-shop-production-492b.up.railway.app/shop-api"
