import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {Toaster} from "@/components/ui/sonner";
import {Navbar} from "@/components/navbar";
import {Footer} from "@/components/footer";
import {AuthProvider} from "@/contexts/auth-context";
import {getActiveCustomer} from "@/lib/vendure/actions";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const activeCustomer = getActiveCustomer();

    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
            >
                <AuthProvider initialActiveCustomerPromise={activeCustomer}>
                    <Navbar />
                    {children}
                    <Footer />
                    <Toaster />
                </AuthProvider>
            </body>
        </html>
    );
}
